language: objective-c
   
osx_image: xcode7.2

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '0.39.0'  

script: 
   xcodebuild -scheme Gojimo-ObjC -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=9.2' test
